"use client";
import {useState} from 'react';
import {ArrowUpRight,ArrowUp,Download,GitFork as Github,ContactRound as Linkedin,Mail,Phone,Box,Code2,Layers,Radio,Minus,Square,Terminal,Plus} from 'lucide-react';
import FeaturedProject from '@/components/sections/FeaturedProject';
import TerminalText from '@/components/animations/TerminalText';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {profile,projects,skills,experience,education,type Project} from '@/data/portfolio';
import ProjectPreview from '@/components/graphics/ProjectPreview';
import Architecture from '@/components/graphics/Architecture';
function WindowBar({children,lime=false}:{children:React.ReactNode;lime?:boolean}){return <div className={`window-bar ${lime?'lime':''}`}><span>{children}</span><span className="window-controls" aria-hidden="true"><Minus/><Square/><Plus className="close-symbol"/></span></div>}
function TerminalPanel(){return <div className="terminal-panel"><WindowBar>terminal.sh</WindowBar><TerminalText/></div>}
export default function Sections(){const [selected,setSelected]=useState<Project|null>(null);const [info,setInfo]=useState<'contact'|'cv'|'about'|null>(null);return <>
<section id="projects" className="projects-section"><div className="section-intro"><span className="section-index">02/</span><h2>SELECTED<br/>PROJECTS</h2><p>Ideas turned into products.<br/>A few things I’ve been working on.</p><span className="intro-bottom mono">2023 — 2026 <ArrowUpRight size={18}/></span></div><div className="project-grid">{projects.map(p=><button key={p.id} className="project-card reveal" onClick={()=>setSelected(p)} aria-label={`View ${p.name} project details`}><div className="preview-wrap"><span className="project-number">{p.id}</span><div className="project-image-motion"><ProjectPreview kind={p.kind}/></div></div><div className="project-info"><span className="project-type mono">{p.type}</span><h3>{p.name}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-foot"><span className="mono">EXPLORE PROJECT</span><span className="arrow-box"><ArrowUpRight size={21}/></span></div></div></button>)}</div></section>
<FeaturedProject onSelect={setSelected}/>
<section className="dashboard"><article className="about-panel reveal" id="about"><div><span className="section-index">03/</span><h2>THE HUMAN<br/>BEHIND THE CODE.</h2></div><div className="about-content"><div className="pixel-avatar" aria-hidden="true"><span className="avatar-face"><i className="avatar-pixel eye-left"/><i className="avatar-pixel eye-right"/><i className="avatar-pixel mouth-left"/><i className="avatar-pixel mouth-center"/><i className="avatar-pixel mouth-right"/></span></div><div><p>{profile.about}</p><button className="text-link mono" onClick={()=>setInfo('about')}>MORE ABOUT ME <ArrowUpRight size={17}/></button></div></div></article><article className="skills-panel reveal" id="skills"><WindowBar>SKILLS.EXE</WindowBar><div className="skill-content">{skills.map(s=><div className="skill" key={s.name}><h3>{s.name}</h3><p>{s.tools}</p><div className="segments" aria-hidden="true">{Array.from({length:16},(_,i)=><i className={i<s.segments?'filled':''} key={i}/>)}</div></div>)}<span className="skill-note mono">ALWAYS LEARNING. ALWAYS ITERATING.</span></div></article><article className="stats-panel reveal"><WindowBar lime>STACK.JSON</WindowBar><div className="stats-grid">{[[Box,'04','PROJECT ENTRIES'],[Code2,'JS/TS','CORE LANGUAGES'],[Radio,'LIVE','REAL-TIME FOCUS'],[Layers,'FULL','STACK THINKING']].map(([Icon,value,label])=>{const I=Icon as typeof Box;return <div key={String(label)}><I size={28}/><span className="stat-mask"><strong className="stat-copy" data-count={/^\d+$/.test(String(value))?String(value):undefined}>{String(value)}</strong></span><span className="mono">{String(label)}</span></div>})}<i className="stat-divider stat-divider-horizontal" aria-hidden="true"/><i className="stat-divider stat-divider-vertical" aria-hidden="true"/></div></article></section>
<section id="experience" className="experience-section"><div className="experience-intro"><span className="section-index">04/</span><h2>BUILDING.<br/>LEARNING.<br/><em>REPEATING.</em></h2><span className="mono">THE JOURNEY SO FAR</span></div><div className="timeline"><span className="timeline-rail" aria-hidden="true"/>{(experience.length?experience:[{year:'PROJECT FOCUS / 01',role:'FULL-STACK PRODUCTS',company:'Personal development',description:'Connecting intuitive interfaces with APIs, authentication and data. Exploring the whole product, from the first component to the final request.',tags:['React','Node.js','MongoDB']},{year:'PROJECT FOCUS / 02',role:'REAL-TIME EXPERIENCES',company:'Technical exploration',description:'Working with shared state, live collaboration and event-driven interfaces. Making complex interactions feel immediate.',tags:['Socket.io','CodeMirror','WebSockets']},{year:'PROJECT FOCUS / 03',role:'SYSTEMS THAT SCALE',company:'Ongoing learning',description:'Building a deeper understanding of application architecture, relational data and reliable deployment workflows.',tags:['Next.js','PostgreSQL','System design']}]).map(e=><article className="timeline-item reveal" key={e.year}><span className="checkpoint"><i className="checkpoint-fill"/></span><div className="experience-copy"><span className="mono year">{e.year}</span><h3>{e.role}</h3><span className="mono company">{e.company}</span><p>{e.description}</p></div><div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>
<div className="marquee" aria-label="React, Next.js, TypeScript, Node.js, PostgreSQL, Socket.io"><div aria-hidden="true">{[0,1].map(i=><span key={i}>REACT <b>✦</b> NEXT.JS <b>✦</b> <em>TYPESCRIPT</em> <b>✦</b> NODE.JS <b>✦</b> POSTGRESQL <b>✦</b> SOCKET.IO <b>✦</b> </span>)}</div></div>
<section className="education-section reveal"><div><span className="section-index">05/</span><h2>EDUCATION &<br/>CERTIFICATIONS</h2></div><div className="education-list">{education.length?education.map(e=><div key={e.title} className="education-row"><span className="mono education-year">{e.year}</span><div className="education-details"><h3>{e.title}</h3><span>{e.organization}</span></div>{e.url&&<a href={e.url} aria-label={`View ${e.title}`}><ArrowUpRight/></a>}</div>):<div className="education-empty"><span className="mono">LEARNING_LOG / IN PROGRESS</span><h3>CURIOSITY IS PART OF THE STACK.</h3><p>Formal education and verified certifications will be added here.</p><span className="mono empty-status">[ DETAILS TO BE UPDATED ]</span></div>}</div></section>
<section className="contact-grid" id="contact"><div className="contact-panel reveal"><span className="grid-signal-track" aria-hidden="true"><i className="grid-signal"/></span><span className="mono">NEXT PROJECT / LET’S TALK</span><h2>LET’S BUILD<br/>SOMETHING<br/>GREAT<span>↗</span></h2><p>Open to development roles, internships, freelance projects and interesting collaborations.</p><button className="button black" onClick={()=>setInfo('contact')}><span className="magnetic-content">START A CONVERSATION <ArrowUpRight/></span></button><div className="hazard" aria-hidden="true"/></div><div className="contact-art" aria-hidden="true"><Architecture/><span className="mono">GOOD IDEAS DESERVE GOOD CODE.</span></div><TerminalPanel/></section>
<footer><div><span className="footer-logo">VS/</span><strong>THANKS FOR<br/>STOPPING BY.</strong></div><span className="mono">© 2026 VINEET SAINI<br/><small>DESIGNED WITH INTENT. BUILT WITH CARE.</small></span><div className="footer-links">{[[Github,profile.github,'GitHub'],[Linkedin,profile.linkedin,'LinkedIn'],[Mail,profile.email?`mailto:${profile.email}`:'','Email']].map(([Icon,url,label])=>{const I=Icon as typeof Mail;return url?<a key={String(label)} href={String(url)} aria-label={String(label)} className="social"><I size={17}/></a>:<button key={String(label)} aria-label={`${label} details`} className="social" onClick={()=>setInfo('contact')}><I size={17}/></button>})}<a className="back-top mono" href="#home">BACK TO TOP <ArrowUp size={17}/></a></div></footer>
<Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="portfolio-dialog">{selected&&<><span className="eyebrow">PROJECT / {selected.id}</span><DialogTitle className="dialog-title">{selected.name}</DialogTitle><DialogDescription className="dialog-description">{selected.detail}</DialogDescription><ProjectPreview kind={selected.kind}/><div className="tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><p className="availability-note">{selected.live||selected.source?"Illustrative interface preview. Explore the actual project using the links below.":"Project concept and illustrative interface. Live and source links have not been provided yet."}</p><div className="actions">{selected.live&&<a href={selected.live} className="button blue">LIVE DEMO <ArrowUpRight/></a>}{selected.source&&<a href={selected.source} className="button">SOURCE CODE <Github/></a>}</div></>}</DialogContent></Dialog>
<Dialog open={!!info} onOpenChange={open=>!open&&setInfo(null)}><DialogContent className="portfolio-dialog"><span className="eyebrow">{info==='about'?'THE PERSON / THE PROCESS':'LET’S CONNECT'}</span><DialogTitle className="dialog-title">{info==='about'?'HELLO, I’M VINEET.':'GOOD WORK STARTS WITH A CONVERSATION.'}</DialogTitle><DialogDescription className="dialog-description">{info==='about'?profile.about:profile.email?'Have an idea, opportunity or an interesting problem? Send me a note.':'Contact details and a downloadable CV are being added. Please check back soon.'}</DialogDescription>{info==='about'?<p>I enjoy the space where thoughtful interfaces meet reliable engineering. My focus is on web products that are useful, readable and enjoyable to use.</p>:<div className="contact-details">{profile.email&&<a className="button blue" href={`mailto:${profile.email}`}>{profile.email}<Mail/></a>}{profile.phone&&<a className="button" href={profile.phoneHref}>{profile.phone}<Phone/></a>}{profile.github&&<a className="button" href={profile.github}>GITHUB <Github/></a>}{profile.linkedin&&<a className="button" href={profile.linkedin}>LINKEDIN <Linkedin/></a>}{profile.cv&&<a className="button" href={profile.cv} download>DOWNLOAD CV <Download/></a>}</div>}</DialogContent></Dialog>
</>}
