"use client";
import { useState, useRef, useLayoutEffect, useCallback } from "react";
import { ArrowUpRight, ArrowDown, Scan, Menu, X } from "lucide-react";
import EntranceLoader from "@/components/animations/EntranceLoader";
import Sections from "@/components/sections/Sections";
import Cursor from "@/components/animations/Cursor";
import {profile} from "@/data/portfolio";
import usePortfolioMotion from "@/components/animations/Animations";
import Architecture from "@/components/graphics/Architecture";
export default function Home(){const [menu,setMenu]=useState(false);const motionRoot=useRef<HTMLElement>(null);const [loading,setLoading]=useState(false);const [introReady,setIntroReady]=useState(false);useLayoutEffect(()=>setLoading(true),[]);const completeIntro=useCallback(()=>{setLoading(false);setIntroReady(true)},[]);usePortfolioMotion(motionRoot,introReady);return <>{loading&&<EntranceLoader onComplete={completeIntro}/>}<main ref={motionRoot} inert={loading}><div id="scroll-progress" aria-hidden="true"/><Cursor/><a className="skip-link" href="#projects">Skip to projects</a><header className="nav"><a className="brand" href="#home"><Scan size={32}/><span>VS/<br/>DEV</span></a><nav className={menu?'open':''}>{['Home','Projects','Experience','Skills','About'].map((x,i)=><a onClick={()=>setMenu(false)} className={i===0?'active':''} href={'#'+x.toLowerCase()} key={x}>0{i+1}_{x.toUpperCase()}</a>)}</nav><a className="connect" href="#contact"><span className="magnetic-content">LET’S CONNECT <ArrowUpRight/></span></a><button className="menu" aria-expanded={menu} aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header><section id="home" className="hero"><div className="hero-copy"><div className="eyebrow"><span/> HELLO, I’M VINEET SAINI</div><h1>FULL STACK<br/>DEVELOPER<span className="blink">_</span></h1><h2>I BUILD SCALABLE,<br/>PERFORMANT AND<br/><em>IMPACTFUL DIGITAL<br/>EXPERIENCES.</em></h2><p>Thoughtful code. Purposeful design.<br/>Digital products built to make a difference.</p><div className="actions"><a className="button blue" href="#projects"><span className="magnetic-content">VIEW MY WORK <ArrowUpRight/></span></a>{profile.cv?<a className="button" href={profile.cv} download>DOWNLOAD CV <ArrowDown/></a>:<button className="button cv-pending" disabled title="A downloadable CV has not been provided yet">CV COMING SOON <ArrowDown/></button>}</div><div className="hero-bottom"><span className="mono">NEW DELHI, INDIA · BUILDING EVERYWHERE</span><a href="#projects" aria-label="Scroll to projects"><ArrowDown size={18}/></a></div></div><div className="hero-art"><div className="art-top mono">FIG. 01 — SYSTEM ARCHITECTURE <span>+ + +</span></div><Architecture/><div className="vertical">AVAILABLE FOR OPPORTUNITIES</div><div className="art-bottom mono"><span><i/> SYSTEM_READY</span><span>DESIGN → DEVELOP → DEPLOY</span></div></div></section><div className="strip mono"><span className="grid-signal-track" aria-hidden="true"><i className="grid-signal"/></span><span>ENGINEERED WITH INTENT.</span><span>SCROLL TO EXPLORE ↓</span><span>PORTFOLIO / 2026</span></div><Sections/></main></>}
